travis:
  secure:
    BINSTAR_TOKEN: NBQOXQhe6J+cvK4/kEeoIEm72393sIHQulNUMqqpoRiUt8+JWRlrd5x24Idj/+hWLGJZTMyU8lCq608gIsqhUKWbcGSF76FLAaax4xHLEKCEh+VsFcI2ZsoF6wFBAIe0L90T8Xdj96gxHPzkUGTkVz6a6urz8HRNpVHDur3tgdHBxM+pjxFcJU5e05LJI4j9oM86G5Z5fQeRc+hovAysysi2ds5FvyNb7jSznJmT1Xizy+wCB/JCJUb5ZSlnp12+LGe9DqT8oEm1sHbK7mGSb9n+4d39aXXkPTRH55/HjzqcnqB3OX9Yqq93S3EHfZXJkezFNh5u9UTTUdQ7Z+J3NZ1LJDFfFZK6ghygaKF88SEO6SyFGgt7yv6Upf1B7a6ycAJDEGNup+kxaQshSBvXOat/SCNnVH3Q8vJ8e2Z2oEhKhQuqRMziIdcEVulDgjbgVynCZTXbKDbh9SJAUx5UV2FMPl/OeK8gQ/8nEch6QNhg54X2qz4BTw87jFJfnN7tphZxG2HCkXgyuNEkMlW42lzwDVWB6xT8oYeRg7ejsiQStw49AiItk+IHHK1Grp5B1pLPOuKAkGEpCPkAqUwiv1z4KodlFjqSdGsbflfbVGesmmCzWZ32t0Hb1h78ZFrNvgksVv9yU6vOIo7+/NSf8m8MYkVcHb64dLNtfd/64jg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
