travis:
  secure:
    BINSTAR_TOKEN: EYSlrxBYUWx2MLqvzYrHuW44f2T3SvmPeJwUZgxQsiSHnVHsKOGHlJaQ+znG0BjT3OOOaamgUG9UB/wwCwddtkte7yRFqd042vZGSa3YXuWdJEZSo5qdk84CT9bDr1JF7EsCjK1L/HYZMSFYvvzrwIy6RhNB2OQFi3cBf4tqnxkMMfc2akDV+e2grGqsGyR9RRpvN7fQc1a4U/7C10T2mZl6Nx9TxJadZT+C6nBD/Up2KqO0KT59wDiw0/jQ0gERwOrMLINpgSuXrRcsQpCD2N4lJ+JlrwRi/oX5kKTppPOd3QW5Z6SpI9He40VdDCDbnki5oQUhcrBTO2Gbo6NeT6AcPNV9qodYttj3a9AcoOfW6k4g7DoLUqW/ceBaIB5BHyyfe/K/YUuUVTHcOah8PpeRLQ9P1zGEtuv5LLCAppMiPn8gDT9CIDdNB/dNUHcOxtMUNIywObOVBnR93J9r7O4gG6EF1KQeD6/XzFg0j2CwjNmWzOnYqYIb36ZPmY8i0UEVImnwLIeBaE7La+2MUmkdg5mYZxQ72TfNrgBfdVTIohL1Fz29DjT6UJghznfAbwR2Hr+wIDcQ/5hl9Zvn1HLQFU50BBWFbDVxvorggdoF8E+HeC1WqEZisB3F9JBZPELzt+kWQRL7HPp3Rhri5Y01rOY6OddZuc1RBl5AuwM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
